[project]
name = "django-genericsite"
dynamic = ["version"]
authors = [{ name = "Vince Veselosky", email = "vince@veselosky.com" }]
description = "basic templates for Django's generic views to produce a decent-looking website with minimal effort"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "django >= 3.2, < 5.0",
    "django-bootstrap-icons >= 0.7.8",
    "pillow >= 2.3.0",
    "easy-thumbnails >= 2.8.4",
    "django-taggit >= 3.0.0, < 4.0",
    "django-tinymce >= 3.4.0, < 3.5",
    "pydantic >= 1.9.1, < 2.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = [
    "black",
    "django-allauth >= 0.51.0",
    "django-debug-toolbar",
    "django_extensions",
    "isort",
    "pip-tools",
    "pycodestyle",
    "pytest",
    "pytest-cov",
    "pytest-django",
]

[project.urls]
"Homepage" = "https://github.com/veselosky/django-genericsite"
"Bug Tracker" = "https://github.com/veselosky/django-genericsite/issues"

[build-system]
# With setuptools-scm, package data files (e.g. templates) that are tracked by git will
# be automatically detected and included. Without setuptools-scm, you would need to
# specify a file pattern in MANIFEST.in to collect them.
requires = ["setuptools>=65.0", "setuptools-scm>=7.0.5", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = { attr = "genericsite.__version__" }
