# Generated by Django 4.2.15 on 2024-08-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("commoncontent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=255)),
                ("ordering", models.IntegerField(default=0)),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Image for the section",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="commoncontent.image",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="commoncontent.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "section image",
                "verbose_name_plural": "section image plugins",
            },
        ),
        migrations.CreateModel(
            name="SectionHTML",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=255)),
                ("ordering", models.IntegerField(default=0)),
                ("html", models.TextField(blank=True, verbose_name="html content")),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="commoncontent.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "section HTML",
                "verbose_name_plural": "section HTML plugins",
            },
        ),
    ]
