# Generated by Django 5.1.7 on 2025-04-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commoncontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, help_text='A subtitle or secondary headline', max_length=255, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='custom_icon',
            field=models.CharField(blank=True, help_text='<a href=https://icons.getbootstrap.com/#icons target=iconlist>icon list</a>', max_length=50, verbose_name='custom icon'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='subtitle',
            field=models.CharField(blank=True, help_text='A subtitle or secondary headline', max_length=255, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='A subtitle or secondary headline', max_length=255, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='image',
            name='custom_icon',
            field=models.CharField(blank=True, help_text='<a href=https://icons.getbootstrap.com/#icons target=iconlist>icon list</a>', max_length=50, verbose_name='custom icon'),
        ),
        migrations.AddField(
            model_name='image',
            name='subtitle',
            field=models.CharField(blank=True, help_text='A subtitle or secondary headline', max_length=255, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='page',
            name='subtitle',
            field=models.CharField(blank=True, help_text='A subtitle or secondary headline', max_length=255, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='section',
            name='subtitle',
            field=models.CharField(blank=True, help_text='A subtitle or secondary headline', max_length=255, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, help_text='An abstract of the content or marketing description. Intended to entice a reader to click through to the content. May contain inline HTML and multiple paragraphs.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='The main headline', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.TextField(blank=True, help_text='An abstract of the content or marketing description. Intended to entice a reader to click through to the content. May contain inline HTML and multiple paragraphs.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=models.TextField(blank=True, help_text='An abstract of the content or marketing description. Intended to entice a reader to click through to the content. May contain inline HTML and multiple paragraphs.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(help_text='The main headline', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, help_text='An abstract of the content or marketing description. Intended to entice a reader to click through to the content. May contain inline HTML and multiple paragraphs.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, help_text='An abstract of the content or marketing description. Intended to entice a reader to click through to the content. May contain inline HTML and multiple paragraphs.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='The main headline', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, help_text='An abstract of the content or marketing description. Intended to entice a reader to click through to the content. May contain inline HTML and multiple paragraphs.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(help_text='The main headline', max_length=255, verbose_name='title'),
        ),
    ]
