# Generated by Django 4.1.4 on 2023-02-03 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("genericsite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="attachment_set",
            field=models.ManyToManyField(
                to="genericsite.attachment", verbose_name="attachments"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image_set",
            field=models.ManyToManyField(
                to="genericsite.image", verbose_name="related images"
            ),
        ),
    ]
