# Generated by Django 4.1.4 on 2023-02-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("genericsite", "0002_attachment_site_image_site_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="alt_text",
            field=models.CharField(blank=True, max_length=255, verbose_name="alt text"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
        migrations.AlterUniqueTogether(
            name="attachment",
            unique_together={("site", "title")},
        ),
        migrations.AlterUniqueTogether(
            name="image",
            unique_together={("site", "title")},
        ),
    ]
