# Generated by Django 4.1.7 on 2023-04-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genericsite", "0003_attachment_alt_text_alter_attachment_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="base_template",
            field=models.CharField(
                blank=True,
                help_text="Replaces the standard base.html root layout. This allows you to have a totally custom layout for a page.",
                max_length=255,
                verbose_name="base template",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content_template",
            field=models.CharField(
                blank=True,
                help_text="The template that renders the content body within the page layout provided by the base.html. This only affects the 'main' section of the page, the rest of the layout is inherited from base.html.",
                max_length=255,
                verbose_name="content body template",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("withheld", "Draft (withheld)"),
                    ("usable", "Publish (usable)"),
                    ("cancelled", "Unpublish (cancelled)"),
                ],
                db_index=True,
                default="usable",
                help_text='Must be "usable" to appear on the site. See <a href="https://schema.org/creativeWorkStatus">Schema.org</a> for details.',
                max_length=50,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="base_template",
            field=models.CharField(
                blank=True,
                help_text="Replaces the standard base.html root layout. This allows you to have a totally custom layout for a page.",
                max_length=255,
                verbose_name="base template",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="content_template",
            field=models.CharField(
                blank=True,
                help_text="The template that renders the content body within the page layout provided by the base.html. This only affects the 'main' section of the page, the rest of the layout is inherited from base.html.",
                max_length=255,
                verbose_name="content body template",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="status",
            field=models.CharField(
                choices=[
                    ("withheld", "Draft (withheld)"),
                    ("usable", "Publish (usable)"),
                    ("cancelled", "Unpublish (cancelled)"),
                ],
                db_index=True,
                default="usable",
                help_text='Must be "usable" to appear on the site. See <a href="https://schema.org/creativeWorkStatus">Schema.org</a> for details.',
                max_length=50,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="type",
            field=models.CharField(
                default="website",
                help_text="Open Graph type, see <a href='https://ogp.me'>https://ogp.me</a>",
                max_length=50,
                verbose_name="opengraph type",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="base_template",
            field=models.CharField(
                blank=True,
                help_text="Replaces the standard base.html root layout. This allows you to have a totally custom layout for a page.",
                max_length=255,
                verbose_name="base template",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="content_template",
            field=models.CharField(
                blank=True,
                help_text="The template that renders the content body within the page layout provided by the base.html. This only affects the 'main' section of the page, the rest of the layout is inherited from base.html.",
                max_length=255,
                verbose_name="content body template",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="status",
            field=models.CharField(
                choices=[
                    ("withheld", "Draft (withheld)"),
                    ("usable", "Publish (usable)"),
                    ("cancelled", "Unpublish (cancelled)"),
                ],
                db_index=True,
                default="usable",
                help_text='Must be "usable" to appear on the site. See <a href="https://schema.org/creativeWorkStatus">Schema.org</a> for details.',
                max_length=50,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="type",
            field=models.CharField(
                default="website",
                help_text="Open Graph type, see <a href='https://ogp.me'>https://ogp.me</a>",
                max_length=50,
                verbose_name="opengraph type",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="base_template",
            field=models.CharField(
                blank=True,
                help_text="Replaces the standard base.html root layout. This allows you to have a totally custom layout for a page.",
                max_length=255,
                verbose_name="base template",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="content_template",
            field=models.CharField(
                blank=True,
                help_text="The template that renders the content body within the page layout provided by the base.html. This only affects the 'main' section of the page, the rest of the layout is inherited from base.html.",
                max_length=255,
                verbose_name="content body template",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="status",
            field=models.CharField(
                choices=[
                    ("withheld", "Draft (withheld)"),
                    ("usable", "Publish (usable)"),
                    ("cancelled", "Unpublish (cancelled)"),
                ],
                db_index=True,
                default="usable",
                help_text='Must be "usable" to appear on the site. See <a href="https://schema.org/creativeWorkStatus">Schema.org</a> for details.',
                max_length=50,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="type",
            field=models.CharField(
                default="website",
                help_text="Open Graph type, see <a href='https://ogp.me'>https://ogp.me</a>",
                max_length=50,
                verbose_name="opengraph type",
            ),
        ),
    ]
