# Generated by Django 4.1.7 on 2023-04-23 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genericsite", "0004_alter_article_base_template_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitevar",
            options={
                "base_manager_name": "objects",
                "verbose_name": "site variable",
                "verbose_name_plural": "site variables",
            },
        ),
    ]
