# Generated by Django 4.1.7 on 2023-04-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genericsite", "0005_alter_sitevar_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="slug",
            field=models.SlugField(
                help_text="Slug 'main-nav' will automatically be included in generic headers.",
                verbose_name="slug",
            ),
        ),
    ]
