# Generated by Django 5.0.2 on 2024-04-14 17:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genericsite", "0006_alter_menu_slug"),
        ("sites", "0002_alter_domain_unique"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "get_latest_by": "date_published",
                "ordering": ["-date_published"],
                "verbose_name": "article",
                "verbose_name_plural": "articles",
            },
        ),
        migrations.AlterModelOptions(
            name="homepage",
            options={
                "get_latest_by": "date_published",
                "ordering": ["-date_published"],
                "verbose_name": "home page",
                "verbose_name_plural": "home pages",
            },
        ),
        migrations.AlterModelOptions(
            name="page",
            options={
                "get_latest_by": "date_published",
                "ordering": ["-date_published"],
                "verbose_name": "page",
                "verbose_name_plural": "pages",
            },
        ),
        migrations.AlterModelOptions(
            name="section",
            options={
                "get_latest_by": "date_published",
                "ordering": ["-date_published"],
                "verbose_name": "section",
                "verbose_name_plural": "sections",
            },
        ),
        migrations.RenameField(
            model_name="article",
            old_name="og_image",
            new_name="share_image",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="og_image",
            new_name="share_image",
        ),
        migrations.RenameField(
            model_name="link",
            old_name="og_image",
            new_name="share_image",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="og_image",
            new_name="share_image",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="og_image",
            new_name="share_image",
        ),
        migrations.AlterUniqueTogether(
            name="article",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="alt_text",
        ),
        migrations.RenameField(
            model_name="attachment",
            old_name="copyright_holder",
            new_name="custom_copyright_holder",
        ),
        migrations.RenameField(
            model_name="attachment",
            old_name="created_dt",
            new_name="date_created",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="image_file",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="image_height",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="image_width",
        ),
        migrations.RenameField(
            model_name="attachment",
            old_name="uploaded_dt",
            new_name="upload_date",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="author_display_name",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="author_profile_url",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="expiration_time",
            new_name="expires",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="modified_time",
            new_name="date_modified",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="published_time",
            new_name="date_published",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="type",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="copyright_holder",
            new_name="custom_copyright_holder",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="created_dt",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="image_height",
            new_name="height",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="image_width",
            new_name="width",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="uploaded_dt",
            new_name="upload_date",
        ),
        migrations.RemoveField(
            model_name="page",
            name="author_display_name",
        ),
        migrations.RemoveField(
            model_name="page",
            name="author_profile_url",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="expiration_time",
            new_name="expires",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="modified_time",
            new_name="date_modified",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="published_time",
            new_name="date_published",
        ),
        migrations.RemoveField(
            model_name="page",
            name="type",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="modified_time",
            new_name="date_modified",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="published_time",
            new_name="date_published",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="expiration_time",
            new_name="expires",
        ),
        migrations.RemoveField(
            model_name="article",
            name="author_display_name",
        ),
        migrations.RemoveField(
            model_name="article",
            name="author_profile_url",
        ),
        migrations.RemoveField(
            model_name="article",
            name="type",
        ),
        migrations.RemoveField(
            model_name="section",
            name="author_display_name",
        ),
        migrations.RemoveField(
            model_name="section",
            name="author_profile_url",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="expiration_time",
            new_name="expires",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="modified_time",
            new_name="date_modified",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="published_time",
            new_name="date_published",
        ),
        migrations.RemoveField(
            model_name="section",
            name="type",
        ),
        migrations.AddField(
            model_name="article",
            name="custom_copyright_holder",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="custom copyright holder"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="date_created",
            field=models.DateTimeField(
                blank=True,
                help_text="When the work was originally created.",
                null=True,
                verbose_name="date created",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created/uploaded the content (for internal permissions, audits).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="date_modified",
            field=models.DateTimeField(
                blank=True,
                help_text="Time of last significant editorial update",
                null=True,
                verbose_name="date modified",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="date_published",
            field=models.DateTimeField(
                blank=True,
                help_text="Must be non-blank and in the past for page to be 'live'",
                null=True,
                verbose_name="date published",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="expires",
            field=models.DateTimeField(
                blank=True,
                help_text="Must be blank or in the future for page to be 'live'",
                null=True,
                verbose_name="expiration date",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="locale",
            field=models.CharField(
                default="en_US", max_length=10, verbose_name="locale"
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created/uploaded the content (for internal permissions, audits).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="status",
            field=models.CharField(
                choices=[
                    ("withheld", "Draft (withheld)"),
                    ("usable", "Publish (usable)"),
                    ("cancelled", "Unpublish (cancelled)"),
                ],
                default="usable",
                help_text='Must be "usable" to appear on the site. See <a href="https://schema.org/creativeWorkStatus">Schema.org</a> for details.',
                max_length=50,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="custom_copyright_holder",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="custom copyright holder"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="date_created",
            field=models.DateTimeField(
                blank=True,
                help_text="When the work was originally created.",
                null=True,
                verbose_name="date created",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created/uploaded the content (for internal permissions, audits).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="date_modified",
            field=models.DateTimeField(
                blank=True,
                help_text="Time of last significant editorial update",
                null=True,
                verbose_name="date modified",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="date_published",
            field=models.DateTimeField(
                blank=True,
                help_text="Must be non-blank and in the past for page to be 'live'",
                null=True,
                verbose_name="date published",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="expires",
            field=models.DateTimeField(
                blank=True,
                help_text="Must be blank or in the future for page to be 'live'",
                null=True,
                verbose_name="expiration date",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="locale",
            field=models.CharField(
                default="en_US", max_length=10, verbose_name="locale"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created/uploaded the content (for internal permissions, audits).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="status",
            field=models.CharField(
                choices=[
                    ("withheld", "Draft (withheld)"),
                    ("usable", "Publish (usable)"),
                    ("cancelled", "Unpublish (cancelled)"),
                ],
                default="usable",
                help_text='Must be "usable" to appear on the site. See <a href="https://schema.org/creativeWorkStatus">Schema.org</a> for details.',
                max_length=50,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="custom_copyright_holder",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="custom copyright holder"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="date_created",
            field=models.DateTimeField(
                blank=True,
                help_text="When the work was originally created.",
                null=True,
                verbose_name="date created",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created/uploaded the content (for internal permissions, audits).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="custom_copyright_holder",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="custom copyright holder"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="date_created",
            field=models.DateTimeField(
                blank=True,
                help_text="When the work was originally created.",
                null=True,
                verbose_name="date created",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created/uploaded the content (for internal permissions, audits).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.TextField(blank=True, verbose_name="body content"),
        ),
        migrations.AlterField(
            model_name="article",
            name="custom_copyright_notice",
            field=models.TextField(
                blank=True,
                help_text="include a pair of curly braces {} where you want the year inserted",
                verbose_name="custom copyright notice",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.site",
                verbose_name="site",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("withheld", "Draft (withheld)"),
                    ("usable", "Publish (usable)"),
                    ("cancelled", "Unpublish (cancelled)"),
                ],
                default="usable",
                help_text='Must be "usable" to appear on the site. See <a href="https://schema.org/creativeWorkStatus">Schema.org</a> for details.',
                max_length=50,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="custom_copyright_notice",
            field=models.TextField(
                blank=True,
                help_text="include a pair of curly braces {} where you want the year inserted",
                verbose_name="custom copyright notice",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.site",
                verbose_name="site",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="title",
            field=models.CharField(blank=True, max_length=255, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=models.TextField(blank=True, verbose_name="body content"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="custom_copyright_notice",
            field=models.TextField(
                blank=True,
                help_text="include a pair of curly braces {} where you want the year inserted",
                verbose_name="custom copyright notice",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.site",
                verbose_name="site",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="status",
            field=models.CharField(
                choices=[
                    ("withheld", "Draft (withheld)"),
                    ("usable", "Publish (usable)"),
                    ("cancelled", "Unpublish (cancelled)"),
                ],
                default="usable",
                help_text='Must be "usable" to appear on the site. See <a href="https://schema.org/creativeWorkStatus">Schema.org</a> for details.',
                max_length=50,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="custom_copyright_notice",
            field=models.TextField(
                blank=True,
                help_text="include a pair of curly braces {} where you want the year inserted",
                verbose_name="custom copyright notice",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_file",
            field=models.ImageField(
                blank=True,
                height_field="height",
                null=True,
                upload_to="",
                verbose_name="image file",
                width_field="width",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.site",
                verbose_name="site",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(blank=True, max_length=255, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="page",
            name="body",
            field=models.TextField(blank=True, verbose_name="body content"),
        ),
        migrations.AlterField(
            model_name="page",
            name="custom_copyright_notice",
            field=models.TextField(
                blank=True,
                help_text="include a pair of curly braces {} where you want the year inserted",
                verbose_name="custom copyright notice",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.site",
                verbose_name="site",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="status",
            field=models.CharField(
                choices=[
                    ("withheld", "Draft (withheld)"),
                    ("usable", "Publish (usable)"),
                    ("cancelled", "Unpublish (cancelled)"),
                ],
                default="usable",
                help_text='Must be "usable" to appear on the site. See <a href="https://schema.org/creativeWorkStatus">Schema.org</a> for details.',
                max_length=50,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="body",
            field=models.TextField(blank=True, verbose_name="body content"),
        ),
        migrations.AlterField(
            model_name="section",
            name="custom_copyright_notice",
            field=models.TextField(
                blank=True,
                help_text="include a pair of curly braces {} where you want the year inserted",
                verbose_name="custom copyright notice",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.site",
                verbose_name="site",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="status",
            field=models.CharField(
                choices=[
                    ("withheld", "Draft (withheld)"),
                    ("usable", "Publish (usable)"),
                    ("cancelled", "Unpublish (cancelled)"),
                ],
                default="usable",
                help_text='Must be "usable" to appear on the site. See <a href="https://schema.org/creativeWorkStatus">Schema.org</a> for details.',
                max_length=50,
                verbose_name="status",
            ),
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Dr. Samuel Clemens, Phd.'",
                        max_length=255,
                        verbose_name="author name, as displayed",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="A brief description of the author, used for SEO description.",
                        max_length=255,
                        verbose_name="description (text only, no markup)",
                    ),
                ),
                (
                    "short_bio",
                    models.TextField(
                        blank=True,
                        help_text="A brief biography of the author, one paragraph. May contain HTML.",
                        verbose_name="short biography",
                    ),
                ),
                (
                    "full_bio",
                    models.TextField(
                        blank=True,
                        help_text="A full biography of the author, main content for the profile page. May contain HTML.",
                        verbose_name="full biography",
                    ),
                ),
                (
                    "copyright_holder",
                    models.CharField(
                        blank=True,
                        help_text="Name of copyright holder for this author.",
                        max_length=255,
                        verbose_name="copyright holder",
                    ),
                ),
                (
                    "copyright_notice",
                    models.TextField(
                        blank=True,
                        help_text="include a pair of curly braces {} where you want the year inserted",
                        verbose_name="custom copyright notice",
                    ),
                ),
                (
                    "profile_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for social sharing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="genericsite.image",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sites.site",
                        verbose_name="site",
                    ),
                ),
                (
                    "social_links",
                    models.ForeignKey(
                        blank=True,
                        help_text="A list of links to the author's websites and/or social media profiles.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="genericsite.menu",
                        verbose_name="social links",
                    ),
                ),
            ],
            options={
                "verbose_name": "author",
                "verbose_name_plural": "authors",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="genericsite.author",
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="genericsite.author",
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="genericsite.author",
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="genericsite.author",
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="genericsite.author",
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="genericsite.author",
                verbose_name="author",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=[
                    "site",
                    "status",
                    "date_published",
                    "expires",
                    "section",
                    "slug",
                ],
                name="genericsite_site_id_e1a778_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="homepage",
            index=models.Index(
                fields=["site", "status", "date_published", "expires", "slug"],
                name="genericsite_site_id_543713_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                fields=["site", "status", "date_published", "expires", "slug"],
                name="genericsite_site_id_282a63_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["site", "status", "date_published", "expires", "slug"],
                name="genericsite_site_id_902711_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                fields=("site", "section", "slug"),
                name="unique_article_slug_per_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("site", "slug"), name="unique_section_slug_per_site"
            ),
        ),
        migrations.AddConstraint(
            model_name="author",
            constraint=models.UniqueConstraint(
                fields=("site", "name"), name="unique_author_name_per_site"
            ),
        ),
    ]
