# Generated by Django 4.2.10 on 2024-04-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genericsite", "0008_author_slug_alter_article_date_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="date_modified",
            field=models.DateTimeField(
                blank=True,
                help_text="Time of last significant editorial update",
                null=True,
                verbose_name="date modified",
            ),
        ),
    ]
