name: Package a release of genericsite
on:
  push:
    tags:
      - "release-*"
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-22.04
    steps:
      - name: Run tests
        uses: .github/workflows/test.yml

      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade build pip setuptools wheel

      - name: Build the release packages
        run: python -m build

      - name: Create a Github Release
        run: gh release create ${{ github.ref }} --generate-notes dist/*
